project_name: Burrow
version: 2

builds:
- main: main.go
  binary: burrow
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
archives:
- formats: [tar.gz]
  format_overrides:
  - goos: windows
    formats: [zip,tar.gz]
  files:
  - LICENSE
  - NOTICE
  - README.md
  - CHANGELOG.md
  - config/burrow.toml
  - config/default-email.tmpl
  - config/default-http-delete.tmpl
  - config/default-http-post.tmpl
  - config/default-slack-delete.tmpl
  - config/default-slack-post.tmpl
snapshot:
  version_template: "{{ .FullCommit }}"
dockers:
- goos: linux
  goarch: amd64
  dockerfile: Dockerfile.gorelease
  image_templates:
  - 'docker.pkg.github.com/linkedin/burrow/burrow:latest'
  - 'docker.pkg.github.com/linkedin/burrow/burrow:latest-amd64'
  - 'docker.pkg.github.com/linkedin/burrow/burrow:{{ .Tag }}'
  - 'docker.pkg.github.com/linkedin/burrow/burrow:{{ .Tag }}-amd64'
  extra_files:
  - docker-config/burrow.toml
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{ .Version }}"
  - "--label=org.label-schema.name={{ .ProjectName }}"
  - "--label=org.label-schema.vcs=https://github.com/linkedin/Burrow"
  - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"

- goos: linux
  goarch: arm64
  dockerfile: Dockerfile.gorelease
  image_templates:
  - 'docker.pkg.github.com/linkedin/burrow/burrow:latest-arm64'
  - 'docker.pkg.github.com/linkedin/burrow/burrow:{{ .Tag }}-arm64'
  extra_files:
  - docker-config/burrow.toml
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{ .Version }}"
  - "--label=org.label-schema.name={{ .ProjectName }}"
  - "--label=org.label-schema.vcs=https://github.com/linkedin/Burrow"
  - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"
docker_manifests:
- name_template: "docker.pkg.github.com/linkedin/burrow/burrow:{{ .Tag }}"
  image_templates:
  - "docker.pkg.github.com/linkedin/burrow/burrow:{{ .Tag }}"
  - "docker.pkg.github.com/linkedin/burrow/burrow:{{ .Tag }}-amd64"
  - "docker.pkg.github.com/linkedin/burrow/burrow:{{ .Tag }}-arm64"
